apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vasist-ingress
  namespace: vasist-ns
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /nginx
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
      - path: /veg
        pathType: Prefix
        backend:
          service:
            name: veg-service
            port:
              number: 80
      - path: /ipl
        pathType: Prefix
        backend:
          service:
            name: ipl-service
            port:
              number: 80
      - path: /netflix
        pathType: Prefix
        backend:
          service:
            name: netflix-service
            port:
              number: 81
      - path: /translate
        pathType: Prefix
        backend:
          service:
            name: translate-service
            port:
              number: 82